[package]
name = "jaab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inline-c = "0.1.7"
petgraph = "0.6.3"
rand = "0.8.5"
tokio = "1.27.0"
